const PALAVRAS_FACIL = [
  "ABRIR","ACHAR","ADIAR","ALIAR","ANDAR","ARMAR","ASSAR","ATUAR",
  "BATER","BEBER","CABER","CALAR","CASAR","CAVAR","CEDER","CEGAR",
  "CITAR","COLAR","COMER","CORAR","COZER","CRIAR","CURAR","DATAR",
  "DETER","DEVER","DIZER","DOMAR","DOTAR","ERRAR","FALAR","FAZER",
  "FERIR","FICAR","FIXAR","FUMAR","FUJIR","HAVER","GELAR","GERAR",
  "GERIR","GOZAR","GUIAR","HAVER","IMPOR","JOGAR","LAVAR","LEVAR",
  "LIDAR","LIGAR","LUTAR","MATAR","MEDIR","METER","MEXER","MIMAR",
  "MINAR","MIRAR","MORAR","MOVER","MUDAR","NADAR","NEGAR","NOTAR",
  "ODIAR","OLHAR","OUVIR","PAGAR","PARAR","PEDIR","PEGAR","PESAR",
  "PICAR","PILAR","PISAR","PODAR","PODER","POLIR","PULAR","PUNIR",
  "PUXAR","REMAR","REZAR","RODAR","ROGAR","SABER","SACAR","SECAR",
  "SELAR","SUBIR","SUJAR","TAPAR","TEMER","TIRAR","TOCAR","TOMAR",
  "TRAIR","UNTAR","VALER","VEDAR","VIRAR","VIVER","ZELAR"
].filter(w => w.length === 5);